{% set name = "pamqp" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 710085aa9ee8f1d6e4df21d3c9a8a20bd0187a6c6875f1bf6d912e8b2e480b74

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pamqp
    - pamqp.frame
    - pamqp.body
    - pamqp.frame
    - pamqp.decode
    - pamqp.encode
    - pamqp.exceptions
    - pamqp.heartbeat
    - pamqp.specification

about:
  home: https://github.com/gmr/pamqp
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pamqp is a pure-python AMQP 0-9-1 frame encoder and decoder
  description: |
    pamqp is a pure-python AMQP 0-9-1 frame encoder and decoder. The aim is to create a client agnostic python encoder and decoder for general purpose use.
  doc_url: https://pamqp.readthedocs.io/
  dev_url: https://github.com/gmr/pamqp

extra:
  recipe-maintainers:
    - gregfreeman
